### ISSUE TITLE
Obstacle course hardening

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/Entrainement#3]
The current obstacle course is manually placed and suffers several minor issues regarding vanilla addactions not being efficiently accessible. This could be avoided by spawning the obstacle courses with a script, hardcoding relative positions and orientations of obstacles. It must also account for terrain elevation variations, for example by lining obstacles over a concrete lane.

**Comment by ArwynFr** [comment]
Consider using new terrain deformation ?
